// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: showtimes.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ShowtimeService_ListShowtimes_FullMethodName = "/showtimes.ShowtimeService/ListShowtimes"
)

// ShowtimeServiceClient is the client API for ShowtimeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShowtimeServiceClient interface {
	// ListShowtimes streams all showtimes from a supported theater
	ListShowtimes(ctx context.Context, in *ListShowtimesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ListShowtimesResponse], error)
}

type showtimeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShowtimeServiceClient(cc grpc.ClientConnInterface) ShowtimeServiceClient {
	return &showtimeServiceClient{cc}
}

func (c *showtimeServiceClient) ListShowtimes(ctx context.Context, in *ListShowtimesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ListShowtimesResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ShowtimeService_ServiceDesc.Streams[0], ShowtimeService_ListShowtimes_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ListShowtimesRequest, ListShowtimesResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ShowtimeService_ListShowtimesClient = grpc.ServerStreamingClient[ListShowtimesResponse]

// ShowtimeServiceServer is the server API for ShowtimeService service.
// All implementations must embed UnimplementedShowtimeServiceServer
// for forward compatibility.
type ShowtimeServiceServer interface {
	// ListShowtimes streams all showtimes from a supported theater
	ListShowtimes(*ListShowtimesRequest, grpc.ServerStreamingServer[ListShowtimesResponse]) error
	mustEmbedUnimplementedShowtimeServiceServer()
}

// UnimplementedShowtimeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedShowtimeServiceServer struct{}

func (UnimplementedShowtimeServiceServer) ListShowtimes(*ListShowtimesRequest, grpc.ServerStreamingServer[ListShowtimesResponse]) error {
	return status.Error(codes.Unimplemented, "method ListShowtimes not implemented")
}
func (UnimplementedShowtimeServiceServer) mustEmbedUnimplementedShowtimeServiceServer() {}
func (UnimplementedShowtimeServiceServer) testEmbeddedByValue()                         {}

// UnsafeShowtimeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShowtimeServiceServer will
// result in compilation errors.
type UnsafeShowtimeServiceServer interface {
	mustEmbedUnimplementedShowtimeServiceServer()
}

func RegisterShowtimeServiceServer(s grpc.ServiceRegistrar, srv ShowtimeServiceServer) {
	// If the following call panics, it indicates UnimplementedShowtimeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ShowtimeService_ServiceDesc, srv)
}

func _ShowtimeService_ListShowtimes_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListShowtimesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ShowtimeServiceServer).ListShowtimes(m, &grpc.GenericServerStream[ListShowtimesRequest, ListShowtimesResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ShowtimeService_ListShowtimesServer = grpc.ServerStreamingServer[ListShowtimesResponse]

// ShowtimeService_ServiceDesc is the grpc.ServiceDesc for ShowtimeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShowtimeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "showtimes.ShowtimeService",
	HandlerType: (*ShowtimeServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListShowtimes",
			Handler:       _ShowtimeService_ListShowtimes_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "showtimes.proto",
}
