// Code generated by protoc-gen-cli. DO NOT EDIT.

package proto

import (
	"context"
	"fmt"
	protocli "github.com/drewfead/proto-cli"
	v3 "github.com/urfave/cli/v3"
	grpc "google.golang.org/grpc"
	insecure "google.golang.org/grpc/credentials/insecure"
	metadata "google.golang.org/grpc/metadata"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	"io"
	"log/slog"
	"os"
	"strconv"
	"strings"
)

// getShowtimeServiceOutputWriter opens the specified output file or returns cmd.Writer (if set) or stdout
func getShowtimeServiceOutputWriter(cmd *v3.Command, path string) (io.Writer, error) {
	if path == "-" || path == "" {
		// Use cmd.Writer if set, otherwise try root command's Writer, otherwise stdout
		if cmd.Writer != nil {
			return cmd.Writer, nil
		}
		if cmd.Root().Writer != nil {
			return cmd.Root().Writer, nil
		}
		return os.Stdout, nil
	}
	return os.Create(path)
}

// parseShowtimeServicePdxSite parses a string value to PdxSite enum
// Accepts enum value names (case-insensitive) or custom CLI names if specified
func parseShowtimeServicePdxSite(value string) (PdxSite, error) {
	// Convert to lowercase for case-insensitive comparison
	lower := strings.ToLower(value)

	// Try parsing as enum value name or custom CLI name
	switch lower {
	case "hollywoodtheatre", "hollywood-theatre":
		return PdxSite_HollywoodTheatre, nil
	case "cinemagic":
		return PdxSite_Cinemagic, nil
	case "cinema21":
		return PdxSite_Cinema21, nil
	}

	// Try parsing as number
	num, err := strconv.ParseInt(value, 10, 32)
	if err == nil {
		return PdxSite(num), nil
	}

	// Invalid value
	return 0, fmt.Errorf("invalid %s value: %q (valid values: %s)", "PdxSite", value, "hollywood-theatre, cinemagic, cinema21")
}

// localServerStream_ShowtimeService_ListShowtimes is a helper type for local server streaming calls to ListShowtimes
type localServerStream_ShowtimeService_ListShowtimes struct {
	ctx       context.Context
	responses chan *ListShowtimesResponse
	errors    chan error
}

func (s *localServerStream_ShowtimeService_ListShowtimes) Send(resp *ListShowtimesResponse) error {
	select {
	case s.responses <- resp:
		return nil
	case <-s.ctx.Done():
		return s.ctx.Err()
	}
}

func (s *localServerStream_ShowtimeService_ListShowtimes) Context() context.Context {
	return s.ctx
}

func (s *localServerStream_ShowtimeService_ListShowtimes) SetHeader(metadata.MD) error {
	return nil
}

func (s *localServerStream_ShowtimeService_ListShowtimes) SendHeader(metadata.MD) error {
	return nil
}

func (s *localServerStream_ShowtimeService_ListShowtimes) SetTrailer(metadata.MD) {}

func (s *localServerStream_ShowtimeService_ListShowtimes) SendMsg(m any) error {
	msg, ok := m.(*ListShowtimesResponse)
	if !ok {
		return fmt.Errorf("invalid message type: expected *%s, got %T", "ListShowtimesResponse", m)
	}
	return s.Send(msg)
}

func (s *localServerStream_ShowtimeService_ListShowtimes) RecvMsg(m any) error {
	return fmt.Errorf("RecvMsg not supported on server streaming")
}

// ShowtimeServiceCommand creates a CLI for ShowtimeService with options
// The implOrFactory parameter can be either a direct service implementation or a factory function
func ShowtimeServiceCommand(ctx context.Context, implOrFactory interface{}, opts ...protocli.ServiceOption) *protocli.ServiceCLI {
	options := protocli.ApplyServiceOptions(opts...)

	// Determine default format (first registered format, or empty if none)
	var defaultFormat string
	if len(options.OutputFormats()) > 0 {
		defaultFormat = options.OutputFormats()[0].Name()
	}

	var commands []*v3.Command

	// Build flags for list-showtimes
	flags_list_showtimes := []v3.Flag{&v3.StringFlag{
		Name:  "remote",
		Usage: "Remote gRPC server address (host:port). If set, uses gRPC client instead of direct call",
	}, &v3.StringFlag{
		Name:  "format",
		Usage: "Output format (use --format to see available formats)",
		Value: defaultFormat,
	}, &v3.StringFlag{
		Name:  "output",
		Usage: "Output file (- for stdout)",
		Value: "-",
	}, &v3.StringFlag{
		Name:  "delimiter",
		Usage: "Delimiter between streamed messages",
		Value: "\n",
	}, &v3.StringFlag{
		Name:  "input-file",
		Usage: "Read request from file (JSON or YAML). CLI flags override file values",
	}, &v3.StringFlag{
		Name:  "input-format",
		Usage: "Input file format (auto-detected from extension if not set)",
	}}

	flags_list_showtimes = append(flags_list_showtimes, &v3.StringSliceFlag{
		DefaultText: "SITE",
		Name:        "from",
		Usage:       "Theater(s) to list showtimes from (hollywood-theatre, cinemagic, cinema21). Repeat for multiple; omit for all. [hollywood-theatre|cinemagic|cinema21]",
	})
	flags_list_showtimes = append(flags_list_showtimes, &v3.StringFlag{
		DefaultText: "TIME",
		Name:        "after",
		Usage:       "Only showtimes after this time (RFC3339)",
	})
	flags_list_showtimes = append(flags_list_showtimes, &v3.StringFlag{
		DefaultText: "TIME",
		Name:        "before",
		Usage:       "Only showtimes before this time (RFC3339)",
	})
	flags_list_showtimes = append(flags_list_showtimes, &v3.Int32Flag{
		DefaultText: "N",
		Name:        "limit",
		Usage:       "Max number of showtimes per page",
	})
	flags_list_showtimes = append(flags_list_showtimes, &v3.StringFlag{
		DefaultText: "TOKEN",
		Name:        "anchor",
		Usage:       "Page token from previous response for pagination",
	})
	flags_list_showtimes = append(flags_list_showtimes, &v3.StringFlag{
		DefaultText: "TZ",
		Name:        "timezone",
		Usage:       "Display times in this IANA timezone (e.g. America/Los_Angeles). Default: CLI local time",
	})

	// Add config field flags for single-command mode

	// Add format-specific flags from registered formats
	for _, outputFmt := range options.OutputFormats() {
		// Check if format implements FlagConfiguredOutputFormat
		if flagConfigured, ok := outputFmt.(protocli.FlagConfiguredOutputFormat); ok {
			flags_list_showtimes = append(flags_list_showtimes, flagConfigured.Flags()...)
		}
	}

	commands = append(commands, &v3.Command{
		Action: func(cmdCtx context.Context, cmd *v3.Command) error {
			defer func() {
				hooks := options.AfterCommandHooks()
				for i := len(hooks) - 1; i >= 0; i-- {
					if err := hooks[i](cmdCtx, cmd); err != nil {
						slog.Warn("after hook failed", "error", err)
					}
				}
			}()

			for _, hook := range options.BeforeCommandHooks() {
				if err := hook(cmdCtx, cmd); err != nil {
					return fmt.Errorf("before hook failed: %w", err)
				}
			}

			// Build request message
			var req *ListShowtimesRequest

			// Check for file-based input
			inputFile := cmd.String("input-file")
			if inputFile != "" {
				// Read request from file
				req = &ListShowtimesRequest{}
				if err := protocli.ReadInputFile(inputFile, cmd.String("input-format"), options.InputFormats(), req); err != nil {
					return err
				}
				// Apply flag overrides (only explicitly-set flags)
				if cmd.IsSet("from") {
					req.From = nil
					for _, s := range cmd.StringSlice("from") {
						val, err := parseShowtimeServicePdxSite(s)
						if err != nil {
							return fmt.Errorf("invalid value for --from: %w", err)
						}
						req.From = append(req.From, val)
					}
				}
				if cmd.IsSet("after") {
					if fieldDeserializer, hasFieldDeserializer := options.FlagDeserializer("google.protobuf.Timestamp"); hasFieldDeserializer {
						fieldFlags := protocli.NewFlagContainer(cmd, "after")
						fieldMsg, fieldErr := fieldDeserializer(cmdCtx, fieldFlags)
						if fieldErr != nil {
							return fmt.Errorf("failed to deserialize field After: %w", fieldErr)
						}
						if fieldMsg != nil {
							typedField, fieldOk := fieldMsg.(*timestamppb.Timestamp)
							if !fieldOk {
								return fmt.Errorf("custom deserializer for google.protobuf.Timestamp returned wrong type: expected *Timestamp, got %T", fieldMsg)
							}
							req.After = typedField
						}
					} else {
						return fmt.Errorf("flag --after requires a custom deserializer for google.protobuf.Timestamp (register with protocli.WithFlagDeserializer)")
					}
				}
				if cmd.IsSet("before") {
					if fieldDeserializer, hasFieldDeserializer := options.FlagDeserializer("google.protobuf.Timestamp"); hasFieldDeserializer {
						fieldFlags := protocli.NewFlagContainer(cmd, "before")
						fieldMsg, fieldErr := fieldDeserializer(cmdCtx, fieldFlags)
						if fieldErr != nil {
							return fmt.Errorf("failed to deserialize field Before: %w", fieldErr)
						}
						if fieldMsg != nil {
							typedField, fieldOk := fieldMsg.(*timestamppb.Timestamp)
							if !fieldOk {
								return fmt.Errorf("custom deserializer for google.protobuf.Timestamp returned wrong type: expected *Timestamp, got %T", fieldMsg)
							}
							req.Before = typedField
						}
					} else {
						return fmt.Errorf("flag --before requires a custom deserializer for google.protobuf.Timestamp (register with protocli.WithFlagDeserializer)")
					}
				}
				if cmd.IsSet("limit") {
					val := cmd.Int32("limit")
					req.Limit = &val
				}
				if cmd.IsSet("anchor") {
					val := cmd.String("anchor")
					req.Anchor = &val
				}
				if cmd.IsSet("output-timezone") {
					val := cmd.String("output-timezone")
					req.OutputTimezone = &val
				}
			} else {
				// Check for custom flag deserializer for showtimes.ListShowtimesRequest
				deserializer, hasDeserializer := options.FlagDeserializer("showtimes.ListShowtimesRequest")
				if hasDeserializer {
					// Use custom deserializer for top-level request
					requestFlags := protocli.NewFlagContainer(cmd, "")
					msg, err := deserializer(cmdCtx, requestFlags)
					if err != nil {
						return fmt.Errorf("custom deserializer failed: %w", err)
					}
					if msg == nil {
						return fmt.Errorf("custom deserializer returned nil message")
					}
					var ok bool
					req, ok = msg.(*ListShowtimesRequest)
					if !ok {
						return fmt.Errorf("custom deserializer returned wrong type: expected *%s, got %T", "ListShowtimesRequest", msg)
					}
				} else {
					// Use auto-generated flag parsing
					req = &ListShowtimesRequest{}
					for _, s := range cmd.StringSlice("from") {
						val, err := parseShowtimeServicePdxSite(s)
						if err != nil {
							return fmt.Errorf("invalid value for --from: %w", err)
						}
						req.From = append(req.From, val)
					}
					// Field After: check for custom deserializer for google.protobuf.Timestamp
					if fieldDeserializer, hasFieldDeserializer := options.FlagDeserializer("google.protobuf.Timestamp"); hasFieldDeserializer {
						// Use custom deserializer for nested message
						// Create FlagContainer for field flag: after
						fieldFlags := protocli.NewFlagContainer(cmd, "after")
						fieldMsg, fieldErr := fieldDeserializer(cmdCtx, fieldFlags)
						if fieldErr != nil {
							return fmt.Errorf("failed to deserialize field After: %w", fieldErr)
						}
						// Handle nil return from deserializer (means skip/use default)
						if fieldMsg != nil {
							typedField, fieldOk := fieldMsg.(*timestamppb.Timestamp)
							if !fieldOk {
								return fmt.Errorf("custom deserializer for google.protobuf.Timestamp returned wrong type: expected *Timestamp, got %T", fieldMsg)
							}
							req.After = typedField
						}
					} else {
						// No custom deserializer - check if user provided a value
						if cmd.IsSet("after") {
							return fmt.Errorf("flag --after requires a custom deserializer for google.protobuf.Timestamp (register with protocli.WithFlagDeserializer)")
						}
						// No value provided - leave field as nil
					}
					// Field Before: check for custom deserializer for google.protobuf.Timestamp
					if fieldDeserializer, hasFieldDeserializer := options.FlagDeserializer("google.protobuf.Timestamp"); hasFieldDeserializer {
						// Use custom deserializer for nested message
						// Create FlagContainer for field flag: before
						fieldFlags := protocli.NewFlagContainer(cmd, "before")
						fieldMsg, fieldErr := fieldDeserializer(cmdCtx, fieldFlags)
						if fieldErr != nil {
							return fmt.Errorf("failed to deserialize field Before: %w", fieldErr)
						}
						// Handle nil return from deserializer (means skip/use default)
						if fieldMsg != nil {
							typedField, fieldOk := fieldMsg.(*timestamppb.Timestamp)
							if !fieldOk {
								return fmt.Errorf("custom deserializer for google.protobuf.Timestamp returned wrong type: expected *Timestamp, got %T", fieldMsg)
							}
							req.Before = typedField
						}
					} else {
						// No custom deserializer - check if user provided a value
						if cmd.IsSet("before") {
							return fmt.Errorf("flag --before requires a custom deserializer for google.protobuf.Timestamp (register with protocli.WithFlagDeserializer)")
						}
						// No value provided - leave field as nil
					}
					if cmd.IsSet("limit") {
						val := cmd.Int32("limit")
						req.Limit = &val
					}
					if cmd.IsSet("anchor") {
						val := cmd.String("anchor")
						req.Anchor = &val
					}
					if cmd.IsSet("output-timezone") {
						val := cmd.String("output-timezone")
						req.OutputTimezone = &val
					}
				}
			}

			// Open output writer
			outputWriter, err := getShowtimeServiceOutputWriter(cmd, cmd.String("output"))
			if err != nil {
				return fmt.Errorf("failed to open output: %w", err)
			}
			if closer, ok := outputWriter.(io.Closer); ok {
				defer closer.Close()
			}

			// Find the appropriate output format
			formatName := cmd.String("format")
			var outputFmt protocli.OutputFormat
			for _, f := range options.OutputFormats() {
				if f.Name() == formatName {
					outputFmt = f
					break
				}
			}
			if outputFmt == nil {
				var availableFormats []string
				for _, f := range options.OutputFormats() {
					availableFormats = append(availableFormats, f.Name())
				}
				return fmt.Errorf("unknown format %q (available: %v)", formatName, availableFormats)
			}

			// Get delimiter for separating streamed messages
			delimiter := cmd.String("delimiter")

			// Check if using remote gRPC call or direct implementation call
			remoteAddr := cmd.String("remote")

			if remoteAddr != "" {
				// Remote gRPC streaming call
				conn, connErr := grpc.NewClient(remoteAddr, grpc.WithTransportCredentials(insecure.NewCredentials()))
				if connErr != nil {
					return fmt.Errorf("failed to connect to remote %s: %w", remoteAddr, connErr)
				}
				defer conn.Close()

				client := NewShowtimeServiceClient(conn)
				stream, err := client.ListShowtimes(cmdCtx, req)
				if err != nil {
					return fmt.Errorf("failed to start stream: %w", err)
				}

				// Receive and format each message in the stream
				var messageCount int
				for {
					msg, recvErr := stream.Recv()
					if recvErr == io.EOF {
						break
					}
					if recvErr != nil {
						return fmt.Errorf("stream receive error: %w", recvErr)
					}

					// Format and write the message
					if err := outputFmt.Format(cmdCtx, cmd, outputWriter, msg); err != nil {
						return fmt.Errorf("format failed: %w", err)
					}

					// Write delimiter
					if _, err := outputWriter.Write([]byte(delimiter)); err != nil {
						return fmt.Errorf("failed to write delimiter: %w", err)
					}
					messageCount++
				}

				// Write final newline to keep terminal clean (only if delimiter doesn't already end with newline)
				if messageCount > 0 && !strings.HasSuffix(delimiter, "\n") {
					if _, err := outputWriter.Write([]byte("\n")); err != nil {
						return fmt.Errorf("failed to write final newline: %w", err)
					}
				}
			} else {
				// Load config and create service implementation
				rootCmd := cmd.Root()
				configPaths := rootCmd.StringSlice("config")
				envPrefix := rootCmd.String("env-prefix")

				loader := protocli.NewConfigLoader(protocli.SingleCommandMode, protocli.FileConfig(configPaths...), protocli.EnvPrefix(envPrefix))

				config := &ShowtimeConfig{}
				if err := loader.LoadServiceConfig(cmd, "showtimeservice", config); err != nil {
					return fmt.Errorf("failed to load config: %w", err)
				}

				svcImpl, err := protocli.CallFactory(implOrFactory, config)
				if err != nil {
					return fmt.Errorf("failed to create service: %w", err)
				}

				// Create local stream wrapper for direct call
				localStream := &localServerStream_ShowtimeService_ListShowtimes{
					ctx:       cmdCtx,
					errors:    make(chan error),
					responses: make(chan *ListShowtimesResponse),
				}

				// Call streaming method in goroutine
				go func() {
					var methodErr error
					methodErr = svcImpl.(ShowtimeServiceServer).ListShowtimes(req, localStream)
					close(localStream.responses)
					if methodErr != nil {
						localStream.errors <- methodErr
					}
					close(localStream.errors)
				}()

				// Receive and format each message in the stream
				var messageCount int
				for {
					select {
					case msg, ok := <-localStream.responses:
						if !ok {
							// Stream closed, check for errors
							if streamErr := <-localStream.errors; streamErr != nil {
								return fmt.Errorf("stream error: %w", streamErr)
							}
							// Write final newline to keep terminal clean (only if delimiter doesn't already end with newline)
							if messageCount > 0 && !strings.HasSuffix(delimiter, "\n") {
								if _, err := outputWriter.Write([]byte("\n")); err != nil {
									return fmt.Errorf("failed to write final newline: %w", err)
								}
							}
							return nil
						}

						// Format and write the message
						if err := outputFmt.Format(cmdCtx, cmd, outputWriter, msg); err != nil {
							return fmt.Errorf("format failed: %w", err)
						}

						// Write delimiter
						if _, err := outputWriter.Write([]byte(delimiter)); err != nil {
							return fmt.Errorf("failed to write delimiter: %w", err)
						}
						messageCount++
					case <-cmdCtx.Done():
						return cmdCtx.Err()
					}
				}
			}

			return nil
		},
		Flags: flags_list_showtimes,
		Name:  "list-showtimes",
		Usage: "Stream showtimes from a theater (Hollywood Theatre, Cinemagic, Cinema 21)",
	})

	return &protocli.ServiceCLI{
		Command: &v3.Command{
			Commands: commands,
			Name:     "showtimes",
			Usage:    "List showtimes from Portland theaters",
		},
		ConfigMessageType: "ShowtimeConfig",
		ConfigPrototype:   &ShowtimeConfig{},
		FactoryOrImpl:     implOrFactory,
		RegisterFunc: func(s *grpc.Server, impl interface{}) {
			RegisterShowtimeServiceServer(s, impl.(ShowtimeServiceServer))
		},
		ServiceName: "showtimes",
	}
}

// ShowtimeServiceCommandsFlat creates a flat command structure for ShowtimeService (for single-service CLIs)
// This returns RPC commands directly at the root level instead of nested under a service command.
// The implOrFactory parameter can be either a direct service implementation or a factory function
// The returned slice includes all RPC commands plus a daemonize command for starting a gRPC server.
func ShowtimeServiceCommandsFlat(ctx context.Context, implOrFactory interface{}, opts ...protocli.ServiceOption) []*v3.Command {
	options := protocli.ApplyServiceOptions(opts...)

	// Determine default format (first registered format, or empty if none)
	var defaultFormat string
	if len(options.OutputFormats()) > 0 {
		defaultFormat = options.OutputFormats()[0].Name()
	}

	var commands []*v3.Command

	// Build flags for list-showtimes
	flags_list_showtimes := []v3.Flag{&v3.StringFlag{
		Name:  "remote",
		Usage: "Remote gRPC server address (host:port). If set, uses gRPC client instead of direct call",
	}, &v3.StringFlag{
		Name:  "format",
		Usage: "Output format (use --format to see available formats)",
		Value: defaultFormat,
	}, &v3.StringFlag{
		Name:  "output",
		Usage: "Output file (- for stdout)",
		Value: "-",
	}, &v3.StringFlag{
		Name:  "delimiter",
		Usage: "Delimiter between streamed messages",
		Value: "\n",
	}, &v3.StringFlag{
		Name:  "input-file",
		Usage: "Read request from file (JSON or YAML). CLI flags override file values",
	}, &v3.StringFlag{
		Name:  "input-format",
		Usage: "Input file format (auto-detected from extension if not set)",
	}}

	flags_list_showtimes = append(flags_list_showtimes, &v3.StringSliceFlag{
		DefaultText: "SITE",
		Name:        "from",
		Usage:       "Theater(s) to list showtimes from (hollywood-theatre, cinemagic, cinema21). Repeat for multiple; omit for all. [hollywood-theatre|cinemagic|cinema21]",
	})
	flags_list_showtimes = append(flags_list_showtimes, &v3.StringFlag{
		DefaultText: "TIME",
		Name:        "after",
		Usage:       "Only showtimes after this time (RFC3339)",
	})
	flags_list_showtimes = append(flags_list_showtimes, &v3.StringFlag{
		DefaultText: "TIME",
		Name:        "before",
		Usage:       "Only showtimes before this time (RFC3339)",
	})
	flags_list_showtimes = append(flags_list_showtimes, &v3.Int32Flag{
		DefaultText: "N",
		Name:        "limit",
		Usage:       "Max number of showtimes per page",
	})
	flags_list_showtimes = append(flags_list_showtimes, &v3.StringFlag{
		DefaultText: "TOKEN",
		Name:        "anchor",
		Usage:       "Page token from previous response for pagination",
	})
	flags_list_showtimes = append(flags_list_showtimes, &v3.StringFlag{
		DefaultText: "TZ",
		Name:        "timezone",
		Usage:       "Display times in this IANA timezone (e.g. America/Los_Angeles). Default: CLI local time",
	})

	// Add config field flags for single-command mode

	// Add format-specific flags from registered formats
	for _, outputFmt := range options.OutputFormats() {
		// Check if format implements FlagConfiguredOutputFormat
		if flagConfigured, ok := outputFmt.(protocli.FlagConfiguredOutputFormat); ok {
			flags_list_showtimes = append(flags_list_showtimes, flagConfigured.Flags()...)
		}
	}

	commands = append(commands, &v3.Command{
		Action: func(cmdCtx context.Context, cmd *v3.Command) error {
			defer func() {
				hooks := options.AfterCommandHooks()
				for i := len(hooks) - 1; i >= 0; i-- {
					if err := hooks[i](cmdCtx, cmd); err != nil {
						slog.Warn("after hook failed", "error", err)
					}
				}
			}()

			for _, hook := range options.BeforeCommandHooks() {
				if err := hook(cmdCtx, cmd); err != nil {
					return fmt.Errorf("before hook failed: %w", err)
				}
			}

			// Build request message
			var req *ListShowtimesRequest

			// Check for file-based input
			inputFile := cmd.String("input-file")
			if inputFile != "" {
				// Read request from file
				req = &ListShowtimesRequest{}
				if err := protocli.ReadInputFile(inputFile, cmd.String("input-format"), options.InputFormats(), req); err != nil {
					return err
				}
				// Apply flag overrides (only explicitly-set flags)
				if cmd.IsSet("from") {
					req.From = nil
					for _, s := range cmd.StringSlice("from") {
						val, err := parseShowtimeServicePdxSite(s)
						if err != nil {
							return fmt.Errorf("invalid value for --from: %w", err)
						}
						req.From = append(req.From, val)
					}
				}
				if cmd.IsSet("after") {
					if fieldDeserializer, hasFieldDeserializer := options.FlagDeserializer("google.protobuf.Timestamp"); hasFieldDeserializer {
						fieldFlags := protocli.NewFlagContainer(cmd, "after")
						fieldMsg, fieldErr := fieldDeserializer(cmdCtx, fieldFlags)
						if fieldErr != nil {
							return fmt.Errorf("failed to deserialize field After: %w", fieldErr)
						}
						if fieldMsg != nil {
							typedField, fieldOk := fieldMsg.(*timestamppb.Timestamp)
							if !fieldOk {
								return fmt.Errorf("custom deserializer for google.protobuf.Timestamp returned wrong type: expected *Timestamp, got %T", fieldMsg)
							}
							req.After = typedField
						}
					} else {
						return fmt.Errorf("flag --after requires a custom deserializer for google.protobuf.Timestamp (register with protocli.WithFlagDeserializer)")
					}
				}
				if cmd.IsSet("before") {
					if fieldDeserializer, hasFieldDeserializer := options.FlagDeserializer("google.protobuf.Timestamp"); hasFieldDeserializer {
						fieldFlags := protocli.NewFlagContainer(cmd, "before")
						fieldMsg, fieldErr := fieldDeserializer(cmdCtx, fieldFlags)
						if fieldErr != nil {
							return fmt.Errorf("failed to deserialize field Before: %w", fieldErr)
						}
						if fieldMsg != nil {
							typedField, fieldOk := fieldMsg.(*timestamppb.Timestamp)
							if !fieldOk {
								return fmt.Errorf("custom deserializer for google.protobuf.Timestamp returned wrong type: expected *Timestamp, got %T", fieldMsg)
							}
							req.Before = typedField
						}
					} else {
						return fmt.Errorf("flag --before requires a custom deserializer for google.protobuf.Timestamp (register with protocli.WithFlagDeserializer)")
					}
				}
				if cmd.IsSet("limit") {
					val := cmd.Int32("limit")
					req.Limit = &val
				}
				if cmd.IsSet("anchor") {
					val := cmd.String("anchor")
					req.Anchor = &val
				}
				if cmd.IsSet("output-timezone") {
					val := cmd.String("output-timezone")
					req.OutputTimezone = &val
				}
			} else {
				// Check for custom flag deserializer for showtimes.ListShowtimesRequest
				deserializer, hasDeserializer := options.FlagDeserializer("showtimes.ListShowtimesRequest")
				if hasDeserializer {
					// Use custom deserializer for top-level request
					requestFlags := protocli.NewFlagContainer(cmd, "")
					msg, err := deserializer(cmdCtx, requestFlags)
					if err != nil {
						return fmt.Errorf("custom deserializer failed: %w", err)
					}
					if msg == nil {
						return fmt.Errorf("custom deserializer returned nil message")
					}
					var ok bool
					req, ok = msg.(*ListShowtimesRequest)
					if !ok {
						return fmt.Errorf("custom deserializer returned wrong type: expected *%s, got %T", "ListShowtimesRequest", msg)
					}
				} else {
					// Use auto-generated flag parsing
					req = &ListShowtimesRequest{}
					for _, s := range cmd.StringSlice("from") {
						val, err := parseShowtimeServicePdxSite(s)
						if err != nil {
							return fmt.Errorf("invalid value for --from: %w", err)
						}
						req.From = append(req.From, val)
					}
					// Field After: check for custom deserializer for google.protobuf.Timestamp
					if fieldDeserializer, hasFieldDeserializer := options.FlagDeserializer("google.protobuf.Timestamp"); hasFieldDeserializer {
						// Use custom deserializer for nested message
						// Create FlagContainer for field flag: after
						fieldFlags := protocli.NewFlagContainer(cmd, "after")
						fieldMsg, fieldErr := fieldDeserializer(cmdCtx, fieldFlags)
						if fieldErr != nil {
							return fmt.Errorf("failed to deserialize field After: %w", fieldErr)
						}
						// Handle nil return from deserializer (means skip/use default)
						if fieldMsg != nil {
							typedField, fieldOk := fieldMsg.(*timestamppb.Timestamp)
							if !fieldOk {
								return fmt.Errorf("custom deserializer for google.protobuf.Timestamp returned wrong type: expected *Timestamp, got %T", fieldMsg)
							}
							req.After = typedField
						}
					} else {
						// No custom deserializer - check if user provided a value
						if cmd.IsSet("after") {
							return fmt.Errorf("flag --after requires a custom deserializer for google.protobuf.Timestamp (register with protocli.WithFlagDeserializer)")
						}
						// No value provided - leave field as nil
					}
					// Field Before: check for custom deserializer for google.protobuf.Timestamp
					if fieldDeserializer, hasFieldDeserializer := options.FlagDeserializer("google.protobuf.Timestamp"); hasFieldDeserializer {
						// Use custom deserializer for nested message
						// Create FlagContainer for field flag: before
						fieldFlags := protocli.NewFlagContainer(cmd, "before")
						fieldMsg, fieldErr := fieldDeserializer(cmdCtx, fieldFlags)
						if fieldErr != nil {
							return fmt.Errorf("failed to deserialize field Before: %w", fieldErr)
						}
						// Handle nil return from deserializer (means skip/use default)
						if fieldMsg != nil {
							typedField, fieldOk := fieldMsg.(*timestamppb.Timestamp)
							if !fieldOk {
								return fmt.Errorf("custom deserializer for google.protobuf.Timestamp returned wrong type: expected *Timestamp, got %T", fieldMsg)
							}
							req.Before = typedField
						}
					} else {
						// No custom deserializer - check if user provided a value
						if cmd.IsSet("before") {
							return fmt.Errorf("flag --before requires a custom deserializer for google.protobuf.Timestamp (register with protocli.WithFlagDeserializer)")
						}
						// No value provided - leave field as nil
					}
					if cmd.IsSet("limit") {
						val := cmd.Int32("limit")
						req.Limit = &val
					}
					if cmd.IsSet("anchor") {
						val := cmd.String("anchor")
						req.Anchor = &val
					}
					if cmd.IsSet("output-timezone") {
						val := cmd.String("output-timezone")
						req.OutputTimezone = &val
					}
				}
			}

			// Open output writer
			outputWriter, err := getShowtimeServiceOutputWriter(cmd, cmd.String("output"))
			if err != nil {
				return fmt.Errorf("failed to open output: %w", err)
			}
			if closer, ok := outputWriter.(io.Closer); ok {
				defer closer.Close()
			}

			// Find the appropriate output format
			formatName := cmd.String("format")
			var outputFmt protocli.OutputFormat
			for _, f := range options.OutputFormats() {
				if f.Name() == formatName {
					outputFmt = f
					break
				}
			}
			if outputFmt == nil {
				var availableFormats []string
				for _, f := range options.OutputFormats() {
					availableFormats = append(availableFormats, f.Name())
				}
				return fmt.Errorf("unknown format %q (available: %v)", formatName, availableFormats)
			}

			// Get delimiter for separating streamed messages
			delimiter := cmd.String("delimiter")

			// Check if using remote gRPC call or direct implementation call
			remoteAddr := cmd.String("remote")

			if remoteAddr != "" {
				// Remote gRPC streaming call
				conn, connErr := grpc.NewClient(remoteAddr, grpc.WithTransportCredentials(insecure.NewCredentials()))
				if connErr != nil {
					return fmt.Errorf("failed to connect to remote %s: %w", remoteAddr, connErr)
				}
				defer conn.Close()

				client := NewShowtimeServiceClient(conn)
				stream, err := client.ListShowtimes(cmdCtx, req)
				if err != nil {
					return fmt.Errorf("failed to start stream: %w", err)
				}

				// Receive and format each message in the stream
				var messageCount int
				for {
					msg, recvErr := stream.Recv()
					if recvErr == io.EOF {
						break
					}
					if recvErr != nil {
						return fmt.Errorf("stream receive error: %w", recvErr)
					}

					// Format and write the message
					if err := outputFmt.Format(cmdCtx, cmd, outputWriter, msg); err != nil {
						return fmt.Errorf("format failed: %w", err)
					}

					// Write delimiter
					if _, err := outputWriter.Write([]byte(delimiter)); err != nil {
						return fmt.Errorf("failed to write delimiter: %w", err)
					}
					messageCount++
				}

				// Write final newline to keep terminal clean (only if delimiter doesn't already end with newline)
				if messageCount > 0 && !strings.HasSuffix(delimiter, "\n") {
					if _, err := outputWriter.Write([]byte("\n")); err != nil {
						return fmt.Errorf("failed to write final newline: %w", err)
					}
				}
			} else {
				// Load config and create service implementation
				rootCmd := cmd.Root()
				configPaths := rootCmd.StringSlice("config")
				envPrefix := rootCmd.String("env-prefix")

				loader := protocli.NewConfigLoader(protocli.SingleCommandMode, protocli.FileConfig(configPaths...), protocli.EnvPrefix(envPrefix))

				config := &ShowtimeConfig{}
				if err := loader.LoadServiceConfig(cmd, "showtimeservice", config); err != nil {
					return fmt.Errorf("failed to load config: %w", err)
				}

				svcImpl, err := protocli.CallFactory(implOrFactory, config)
				if err != nil {
					return fmt.Errorf("failed to create service: %w", err)
				}

				// Create local stream wrapper for direct call
				localStream := &localServerStream_ShowtimeService_ListShowtimes{
					ctx:       cmdCtx,
					errors:    make(chan error),
					responses: make(chan *ListShowtimesResponse),
				}

				// Call streaming method in goroutine
				go func() {
					var methodErr error
					methodErr = svcImpl.(ShowtimeServiceServer).ListShowtimes(req, localStream)
					close(localStream.responses)
					if methodErr != nil {
						localStream.errors <- methodErr
					}
					close(localStream.errors)
				}()

				// Receive and format each message in the stream
				var messageCount int
				for {
					select {
					case msg, ok := <-localStream.responses:
						if !ok {
							// Stream closed, check for errors
							if streamErr := <-localStream.errors; streamErr != nil {
								return fmt.Errorf("stream error: %w", streamErr)
							}
							// Write final newline to keep terminal clean (only if delimiter doesn't already end with newline)
							if messageCount > 0 && !strings.HasSuffix(delimiter, "\n") {
								if _, err := outputWriter.Write([]byte("\n")); err != nil {
									return fmt.Errorf("failed to write final newline: %w", err)
								}
							}
							return nil
						}

						// Format and write the message
						if err := outputFmt.Format(cmdCtx, cmd, outputWriter, msg); err != nil {
							return fmt.Errorf("format failed: %w", err)
						}

						// Write delimiter
						if _, err := outputWriter.Write([]byte(delimiter)); err != nil {
							return fmt.Errorf("failed to write delimiter: %w", err)
						}
						messageCount++
					case <-cmdCtx.Done():
						return cmdCtx.Err()
					}
				}
			}

			return nil
		},
		Flags: flags_list_showtimes,
		Name:  "list-showtimes",
		Usage: "Stream showtimes from a theater (Hollywood Theatre, Cinemagic, Cinema 21)",
	})

	// Create ServiceCLI for daemonize command
	serviceCLI := &protocli.ServiceCLI{
		ConfigMessageType: "ShowtimeConfig",
		ConfigPrototype:   &ShowtimeConfig{},
		FactoryOrImpl:     implOrFactory,
		RegisterFunc: func(s *grpc.Server, impl interface{}) {
			RegisterShowtimeServiceServer(s, impl.(ShowtimeServiceServer))
		},
		ServiceName: "showtimes",
	}

	// Create daemonize command for starting gRPC server
	daemonCmd := protocli.NewDaemonizeCommand(ctx, []*protocli.ServiceCLI{serviceCLI}, options)

	// Append daemonize command to the list
	commands = append(commands, daemonCmd)

	return commands
}
