// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: showtimes.proto

package proto

import (
	_ "github.com/drewfead/proto-cli/proto/cli/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PdxSite int32

const (
	PdxSite_None             PdxSite = 0
	PdxSite_HollywoodTheatre PdxSite = 1
)

// Enum value maps for PdxSite.
var (
	PdxSite_name = map[int32]string{
		0: "None",
		1: "HollywoodTheatre",
	}
	PdxSite_value = map[string]int32{
		"None":             0,
		"HollywoodTheatre": 1,
	}
)

func (x PdxSite) Enum() *PdxSite {
	p := new(PdxSite)
	*p = x
	return p
}

func (x PdxSite) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PdxSite) Descriptor() protoreflect.EnumDescriptor {
	return file_showtimes_proto_enumTypes[0].Descriptor()
}

func (PdxSite) Type() protoreflect.EnumType {
	return &file_showtimes_proto_enumTypes[0]
}

func (x PdxSite) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PdxSite.Descriptor instead.
func (PdxSite) EnumDescriptor() ([]byte, []int) {
	return file_showtimes_proto_rawDescGZIP(), []int{0}
}

type ListShowtimesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	From  PdxSite                `protobuf:"varint,1,opt,name=from,proto3,enum=showtimes.PdxSite" json:"from,omitempty"`
	// Time filtering options (mutually exclusive with after/before)
	After         *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=after,proto3,oneof" json:"after,omitempty"`   // only events after this time
	Before        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=before,proto3,oneof" json:"before,omitempty"` // only events before this time
	Limit         *int32                 `protobuf:"varint,6,opt,name=limit,proto3,oneof" json:"limit,omitempty"`  // page size (number of events per page)
	Anchor        *string                `protobuf:"bytes,7,opt,name=anchor,proto3,oneof" json:"anchor,omitempty"` // token for retrieving the next page of results
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListShowtimesRequest) Reset() {
	*x = ListShowtimesRequest{}
	mi := &file_showtimes_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListShowtimesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListShowtimesRequest) ProtoMessage() {}

func (x *ListShowtimesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_showtimes_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListShowtimesRequest.ProtoReflect.Descriptor instead.
func (*ListShowtimesRequest) Descriptor() ([]byte, []int) {
	return file_showtimes_proto_rawDescGZIP(), []int{0}
}

func (x *ListShowtimesRequest) GetFrom() PdxSite {
	if x != nil {
		return x.From
	}
	return PdxSite_None
}

func (x *ListShowtimesRequest) GetAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.After
	}
	return nil
}

func (x *ListShowtimesRequest) GetBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.Before
	}
	return nil
}

func (x *ListShowtimesRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *ListShowtimesRequest) GetAnchor() string {
	if x != nil && x.Anchor != nil {
		return *x.Anchor
	}
	return ""
}

type ListShowtimesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Showtime      *Showtime              `protobuf:"bytes,1,opt,name=showtime,proto3" json:"showtime,omitempty"`                             // the showtime (present for all messages except potentially the last)
	NextAnchor    *string                `protobuf:"bytes,2,opt,name=next_anchor,json=nextAnchor,proto3,oneof" json:"next_anchor,omitempty"` // token for the next page (only set on the last message if more results exist)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListShowtimesResponse) Reset() {
	*x = ListShowtimesResponse{}
	mi := &file_showtimes_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListShowtimesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListShowtimesResponse) ProtoMessage() {}

func (x *ListShowtimesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_showtimes_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListShowtimesResponse.ProtoReflect.Descriptor instead.
func (*ListShowtimesResponse) Descriptor() ([]byte, []int) {
	return file_showtimes_proto_rawDescGZIP(), []int{1}
}

func (x *ListShowtimesResponse) GetShowtime() *Showtime {
	if x != nil {
		return x.Showtime
	}
	return nil
}

func (x *ListShowtimesResponse) GetNextAnchor() string {
	if x != nil && x.NextAnchor != nil {
		return *x.NextAnchor
	}
	return ""
}

type Showtime struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Summary       string                 `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3,oneof" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3,oneof" json:"end_time,omitempty"`
	Location      *string                `protobuf:"bytes,6,opt,name=location,proto3,oneof" json:"location,omitempty"`
	Screening     *ScreeningInfo         `protobuf:"bytes,10,opt,name=screening,proto3" json:"screening,omitempty"`
	Movie         *MovieInfo             `protobuf:"bytes,11,opt,name=movie,proto3" json:"movie,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Showtime) Reset() {
	*x = Showtime{}
	mi := &file_showtimes_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Showtime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Showtime) ProtoMessage() {}

func (x *Showtime) ProtoReflect() protoreflect.Message {
	mi := &file_showtimes_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Showtime.ProtoReflect.Descriptor instead.
func (*Showtime) Descriptor() ([]byte, []int) {
	return file_showtimes_proto_rawDescGZIP(), []int{2}
}

func (x *Showtime) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Showtime) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Showtime) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Showtime) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *Showtime) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *Showtime) GetLocation() string {
	if x != nil && x.Location != nil {
		return *x.Location
	}
	return ""
}

func (x *Showtime) GetScreening() *ScreeningInfo {
	if x != nil {
		return x.Screening
	}
	return nil
}

func (x *Showtime) GetMovie() *MovieInfo {
	if x != nil {
		return x.Movie
	}
	return nil
}

type ScreeningInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         *string                `protobuf:"bytes,1,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Series        *string                `protobuf:"bytes,2,opt,name=series,proto3,oneof" json:"series,omitempty"`
	Host          *string                `protobuf:"bytes,3,opt,name=host,proto3,oneof" json:"host,omitempty"`
	Subhed        *string                `protobuf:"bytes,4,opt,name=subhed,proto3,oneof" json:"subhed,omitempty"` // e.g. "in 35mm" from venue listing
	Links         []*Link                `protobuf:"bytes,10,rep,name=links,proto3" json:"links,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScreeningInfo) Reset() {
	*x = ScreeningInfo{}
	mi := &file_showtimes_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreeningInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreeningInfo) ProtoMessage() {}

func (x *ScreeningInfo) ProtoReflect() protoreflect.Message {
	mi := &file_showtimes_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreeningInfo.ProtoReflect.Descriptor instead.
func (*ScreeningInfo) Descriptor() ([]byte, []int) {
	return file_showtimes_proto_rawDescGZIP(), []int{3}
}

func (x *ScreeningInfo) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *ScreeningInfo) GetSeries() string {
	if x != nil && x.Series != nil {
		return *x.Series
	}
	return ""
}

func (x *ScreeningInfo) GetHost() string {
	if x != nil && x.Host != nil {
		return *x.Host
	}
	return ""
}

func (x *ScreeningInfo) GetSubhed() string {
	if x != nil && x.Subhed != nil {
		return *x.Subhed
	}
	return ""
}

func (x *ScreeningInfo) GetLinks() []*Link {
	if x != nil {
		return x.Links
	}
	return nil
}

type MovieInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         *string                `protobuf:"bytes,1,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Tagline       *string                `protobuf:"bytes,2,opt,name=tagline,proto3,oneof" json:"tagline,omitempty"`
	Overview      *string                `protobuf:"bytes,3,opt,name=overview,proto3,oneof" json:"overview,omitempty"`
	Links         []*Link                `protobuf:"bytes,10,rep,name=links,proto3" json:"links,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovieInfo) Reset() {
	*x = MovieInfo{}
	mi := &file_showtimes_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovieInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovieInfo) ProtoMessage() {}

func (x *MovieInfo) ProtoReflect() protoreflect.Message {
	mi := &file_showtimes_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovieInfo.ProtoReflect.Descriptor instead.
func (*MovieInfo) Descriptor() ([]byte, []int) {
	return file_showtimes_proto_rawDescGZIP(), []int{4}
}

func (x *MovieInfo) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *MovieInfo) GetTagline() string {
	if x != nil && x.Tagline != nil {
		return *x.Tagline
	}
	return ""
}

func (x *MovieInfo) GetOverview() string {
	if x != nil && x.Overview != nil {
		return *x.Overview
	}
	return ""
}

func (x *MovieInfo) GetLinks() []*Link {
	if x != nil {
		return x.Links
	}
	return nil
}

type Link struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Href          string                 `protobuf:"bytes,1,opt,name=href,proto3" json:"href,omitempty"`
	Display       *string                `protobuf:"bytes,10,opt,name=display,proto3,oneof" json:"display,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Link) Reset() {
	*x = Link{}
	mi := &file_showtimes_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Link) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Link) ProtoMessage() {}

func (x *Link) ProtoReflect() protoreflect.Message {
	mi := &file_showtimes_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Link.ProtoReflect.Descriptor instead.
func (*Link) Descriptor() ([]byte, []int) {
	return file_showtimes_proto_rawDescGZIP(), []int{5}
}

func (x *Link) GetHref() string {
	if x != nil {
		return x.Href
	}
	return ""
}

func (x *Link) GetDisplay() string {
	if x != nil && x.Display != nil {
		return *x.Display
	}
	return ""
}

type ShowtimeConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tmdb          *TMDBConfig            `protobuf:"bytes,1,opt,name=tmdb,proto3" json:"tmdb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowtimeConfig) Reset() {
	*x = ShowtimeConfig{}
	mi := &file_showtimes_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowtimeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowtimeConfig) ProtoMessage() {}

func (x *ShowtimeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_showtimes_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowtimeConfig.ProtoReflect.Descriptor instead.
func (*ShowtimeConfig) Descriptor() ([]byte, []int) {
	return file_showtimes_proto_rawDescGZIP(), []int{6}
}

func (x *ShowtimeConfig) GetTmdb() *TMDBConfig {
	if x != nil {
		return x.Tmdb
	}
	return nil
}

type TMDBConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TMDBConfig) Reset() {
	*x = TMDBConfig{}
	mi := &file_showtimes_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TMDBConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TMDBConfig) ProtoMessage() {}

func (x *TMDBConfig) ProtoReflect() protoreflect.Message {
	mi := &file_showtimes_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TMDBConfig.ProtoReflect.Descriptor instead.
func (*TMDBConfig) Descriptor() ([]byte, []int) {
	return file_showtimes_proto_rawDescGZIP(), []int{7}
}

func (x *TMDBConfig) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

var File_showtimes_proto protoreflect.FileDescriptor

const file_showtimes_proto_rawDesc = "" +
	"\n" +
	"\x0fshowtimes.proto\x12\tshowtimes\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x16proto/cli/v1/cli.proto\"\x90\x02\n" +
	"\x14ListShowtimesRequest\x12&\n" +
	"\x04from\x18\x01 \x01(\x0e2\x12.showtimes.PdxSiteR\x04from\x125\n" +
	"\x05after\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x05after\x88\x01\x01\x127\n" +
	"\x06before\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\x06before\x88\x01\x01\x12\x19\n" +
	"\x05limit\x18\x06 \x01(\x05H\x02R\x05limit\x88\x01\x01\x12\x1b\n" +
	"\x06anchor\x18\a \x01(\tH\x03R\x06anchor\x88\x01\x01B\b\n" +
	"\x06_afterB\t\n" +
	"\a_beforeB\b\n" +
	"\x06_limitB\t\n" +
	"\a_anchor\"~\n" +
	"\x15ListShowtimesResponse\x12/\n" +
	"\bshowtime\x18\x01 \x01(\v2\x13.showtimes.ShowtimeR\bshowtime\x12$\n" +
	"\vnext_anchor\x18\x02 \x01(\tH\x00R\n" +
	"nextAnchor\x88\x01\x01B\x0e\n" +
	"\f_next_anchor\"\x95\x03\n" +
	"\bShowtime\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\asummary\x18\x02 \x01(\tR\asummary\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01\x12>\n" +
	"\n" +
	"start_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\tstartTime\x88\x01\x01\x12:\n" +
	"\bend_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x02R\aendTime\x88\x01\x01\x12\x1f\n" +
	"\blocation\x18\x06 \x01(\tH\x03R\blocation\x88\x01\x01\x126\n" +
	"\tscreening\x18\n" +
	" \x01(\v2\x18.showtimes.ScreeningInfoR\tscreening\x12*\n" +
	"\x05movie\x18\v \x01(\v2\x14.showtimes.MovieInfoR\x05movieB\x0e\n" +
	"\f_descriptionB\r\n" +
	"\v_start_timeB\v\n" +
	"\t_end_timeB\v\n" +
	"\t_location\"\xcd\x01\n" +
	"\rScreeningInfo\x12\x19\n" +
	"\x05title\x18\x01 \x01(\tH\x00R\x05title\x88\x01\x01\x12\x1b\n" +
	"\x06series\x18\x02 \x01(\tH\x01R\x06series\x88\x01\x01\x12\x17\n" +
	"\x04host\x18\x03 \x01(\tH\x02R\x04host\x88\x01\x01\x12\x1b\n" +
	"\x06subhed\x18\x04 \x01(\tH\x03R\x06subhed\x88\x01\x01\x12%\n" +
	"\x05links\x18\n" +
	" \x03(\v2\x0f.showtimes.LinkR\x05linksB\b\n" +
	"\x06_titleB\t\n" +
	"\a_seriesB\a\n" +
	"\x05_hostB\t\n" +
	"\a_subhed\"\xb0\x01\n" +
	"\tMovieInfo\x12\x19\n" +
	"\x05title\x18\x01 \x01(\tH\x00R\x05title\x88\x01\x01\x12\x1d\n" +
	"\atagline\x18\x02 \x01(\tH\x01R\atagline\x88\x01\x01\x12\x1f\n" +
	"\boverview\x18\x03 \x01(\tH\x02R\boverview\x88\x01\x01\x12%\n" +
	"\x05links\x18\n" +
	" \x03(\v2\x0f.showtimes.LinkR\x05linksB\b\n" +
	"\x06_titleB\n" +
	"\n" +
	"\b_taglineB\v\n" +
	"\t_overview\"E\n" +
	"\x04Link\x12\x12\n" +
	"\x04href\x18\x01 \x01(\tR\x04href\x12\x1d\n" +
	"\adisplay\x18\n" +
	" \x01(\tH\x00R\adisplay\x88\x01\x01B\n" +
	"\n" +
	"\b_display\";\n" +
	"\x0eShowtimeConfig\x12)\n" +
	"\x04tmdb\x18\x01 \x01(\v2\x15.showtimes.TMDBConfigR\x04tmdb\"%\n" +
	"\n" +
	"TMDBConfig\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey*)\n" +
	"\aPdxSite\x12\b\n" +
	"\x04None\x10\x00\x12\x14\n" +
	"\x10HollywoodTheatre\x10\x012}\n" +
	"\x0fShowtimeService\x12T\n" +
	"\rListShowtimes\x12\x1f.showtimes.ListShowtimesRequest\x1a .showtimes.ListShowtimesResponse0\x01\x1a\x14\x9a\xb5\x18\x10\n" +
	"\x0eShowtimeConfigB'Z%github.com/drewfead/pdx-watcher/protob\x06proto3"

var (
	file_showtimes_proto_rawDescOnce sync.Once
	file_showtimes_proto_rawDescData []byte
)

func file_showtimes_proto_rawDescGZIP() []byte {
	file_showtimes_proto_rawDescOnce.Do(func() {
		file_showtimes_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_showtimes_proto_rawDesc), len(file_showtimes_proto_rawDesc)))
	})
	return file_showtimes_proto_rawDescData
}

var file_showtimes_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_showtimes_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_showtimes_proto_goTypes = []any{
	(PdxSite)(0),                  // 0: showtimes.PdxSite
	(*ListShowtimesRequest)(nil),  // 1: showtimes.ListShowtimesRequest
	(*ListShowtimesResponse)(nil), // 2: showtimes.ListShowtimesResponse
	(*Showtime)(nil),              // 3: showtimes.Showtime
	(*ScreeningInfo)(nil),         // 4: showtimes.ScreeningInfo
	(*MovieInfo)(nil),             // 5: showtimes.MovieInfo
	(*Link)(nil),                  // 6: showtimes.Link
	(*ShowtimeConfig)(nil),        // 7: showtimes.ShowtimeConfig
	(*TMDBConfig)(nil),            // 8: showtimes.TMDBConfig
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_showtimes_proto_depIdxs = []int32{
	0,  // 0: showtimes.ListShowtimesRequest.from:type_name -> showtimes.PdxSite
	9,  // 1: showtimes.ListShowtimesRequest.after:type_name -> google.protobuf.Timestamp
	9,  // 2: showtimes.ListShowtimesRequest.before:type_name -> google.protobuf.Timestamp
	3,  // 3: showtimes.ListShowtimesResponse.showtime:type_name -> showtimes.Showtime
	9,  // 4: showtimes.Showtime.start_time:type_name -> google.protobuf.Timestamp
	9,  // 5: showtimes.Showtime.end_time:type_name -> google.protobuf.Timestamp
	4,  // 6: showtimes.Showtime.screening:type_name -> showtimes.ScreeningInfo
	5,  // 7: showtimes.Showtime.movie:type_name -> showtimes.MovieInfo
	6,  // 8: showtimes.ScreeningInfo.links:type_name -> showtimes.Link
	6,  // 9: showtimes.MovieInfo.links:type_name -> showtimes.Link
	8,  // 10: showtimes.ShowtimeConfig.tmdb:type_name -> showtimes.TMDBConfig
	1,  // 11: showtimes.ShowtimeService.ListShowtimes:input_type -> showtimes.ListShowtimesRequest
	2,  // 12: showtimes.ShowtimeService.ListShowtimes:output_type -> showtimes.ListShowtimesResponse
	12, // [12:13] is the sub-list for method output_type
	11, // [11:12] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_showtimes_proto_init() }
func file_showtimes_proto_init() {
	if File_showtimes_proto != nil {
		return
	}
	file_showtimes_proto_msgTypes[0].OneofWrappers = []any{}
	file_showtimes_proto_msgTypes[1].OneofWrappers = []any{}
	file_showtimes_proto_msgTypes[2].OneofWrappers = []any{}
	file_showtimes_proto_msgTypes[3].OneofWrappers = []any{}
	file_showtimes_proto_msgTypes[4].OneofWrappers = []any{}
	file_showtimes_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_showtimes_proto_rawDesc), len(file_showtimes_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_showtimes_proto_goTypes,
		DependencyIndexes: file_showtimes_proto_depIdxs,
		EnumInfos:         file_showtimes_proto_enumTypes,
		MessageInfos:      file_showtimes_proto_msgTypes,
	}.Build()
	File_showtimes_proto = out.File
	file_showtimes_proto_goTypes = nil
	file_showtimes_proto_depIdxs = nil
}
